version: '3.0'

expectations:
  population_size: 100

actions:

  # generate cohorts
  generate_study_population_precovid:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-01-01 to 2020-01-01 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_2020-01-01.csv

  generate_study_population_covid:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-01-01 to 2021-01-01 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_2021-01-01.csv

  # analyse cohorts
  describe_precovid:
    run: r:latest analysis/cohort_report.R 2020-01-01
    needs: [generate_study_population_precovid]
    outputs:
      moderately_sensitive:
        n_prescribing_table: output/n_prescribing_2020-01-01.csv
        n_indications_table: output/n_indications_2020-01-01.csv
        n_indications_co_occurrence_table: output/n_indications_co_occurrence_2020-01-01.csv
        n_repeat_amr_table: output/n_repeat_amr_2020-01-01.csv
        demographics_table: output/demographics_table_2020-01-01.csv

  describe_covid:
    run: r:latest analysis/cohort_report.R 2021-01-01
    needs: [generate_study_population_covid]
    outputs:
      moderately_sensitive:
        n_prescribing_table: output/n_prescribing_2021-01-01.csv
        n_indications_table: output/n_indications_2021-01-01.csv
        n_indications_co_occurrence_table: output/n_indications_co_occurrence_2021-01-01.csv
        n_repeat_amr_table: output/n_repeat_amr_2021-01-01.csv
        demographics_table: output/demographics_table_2021-01-01.csv

  # generate measures
  generate_measure_populations:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_measures --index-date-range "2020-01-01 to 2022-01-01 by month" --output-dir=output/measures
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_measures --output-dir=output/measures
    needs: [generate_measure_populations]
    outputs:
      moderately_sensitive:
        measure_csv: output/measures/measure_*.csv

  describe_measures:
    run: r:latest analysis/measures_report.R
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        measures_figure: output/measures/measure_prescribing.png
